<?php
/*
 * Copyright 2022 LABOR.digital
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Last modified: 2022.05.13 at 11:55
 */

/***************************************************************
 * Extension Manager/Repository config file for ext: "th_bingen"
 *
 * Auto generated by Extension Builder 2016-03-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title'            => 'Distributed cache clearing',
    'description'      => 'Handler to clear the cache in multi-container setups',
    'category'         => 'be',
    'author'           => 'LABOR GmbH',
    'author_email'     => 'm.neundorfer@labor.digital',
    'state'            => 'stable',
    'internal'         => '',
    'uploadfolder'     => '0',
    'createDirs'       => '',
    'clearCacheOnLoad' => 0,
    'version'          => '9.0.0',
    'constraints'      => [
        'depends'   => [
            'typo3' => '9.0.0-9.99.99',
        ],
        'conflicts' => [
        ],
        'suggests'  => [
        ],
    ],
];
